name: Warper
version: 0.1
author: NeoPrince
website: http://midgard-journey.com
main: com.midgardjourney.warper.WarperPlugin
softdepend: [Citizens]
commands:
   warper:
      description: zeigt alle kommandos fuer das NPC warper plugin an
      usage: /warper
      permission: warper.admin
      permission-message: keine Berechtigung
   dungeon:
      description: komandos die zum dungeon gehoeren
      usage: /dungeon [befehl] {params}
      permission: warper.dungeon
      permission-message: keine Berechtigung               
permissions:
   warper.dungeon.leave.others:
     description: ermoeglicht es andere Spieler aus einem Dungeon zu holen
     default: op 
   warper.dungeon.bypasscmd:
     description: ermoeglicht es in einem Dungeon Befehle zu benutzen
     default: op